"""ActiveGraph-native automation application seam."""

from harness.automation.application import (
    AmbiguousWriteError,
    ApprovalError,
    ApprovalGrant,
    AuthorityError,
    AutomationApplication,
    AutomationDefinition,
    BudgetExhaustedError,
    DuplicateWriteError,
    EvidenceReference,
    MappingSecretAdapter,
    ReconciliationError,
    ReconciliationResult,
    ReplayDivergenceError,
    RepairError,
    RepairProposal,
    RepairTrialResult,
    RepeatedTransitionError,
    RunBudget,
    RunSummary,
    ToolResult,
    VerificationResult,
    WorkspaceRuntimeActiveError,
)
from harness.automation.authoring import (
    AutomationAction,
    AutomationIntent,
    AutomationProposal,
    DefinitionVersion,
    DiscoveryAdapter,
    DiscoveryEvidence,
    ProposalBudget,
    ProposalModelAdapter,
    ProposalValidation,
    ProposalValidationError,
    SelectorEvidence,
    proposal_from_dict,
)
from harness.automation.capabilities import (
    ACTION_CLASSES,
    CapabilityExecutor,
    CapabilityOp,
    FakeApi,
    FakeBrowser,
    FakeDesktop,
    FakeExcel,
)
from harness.automation.evidence import export_run_evidence, run_evidence_payload
from harness.automation.evidence import EvidenceStore
from harness.automation.interface import ApplicationResult, Command, Query
from harness.automation.principals import Principal, PrincipalError
from harness.automation.source_validation import (
    ActionManifest,
    SourceValidation,
    SourceValidationError,
    revision_identity,
    validate_source,
)
from harness.automation.skills import FeatureSkill, discover_skills, get_skill
from harness.automation.scheduler import (
    ScheduledTaskRecord,
    ScheduledTaskSpec,
    SchedulerCapabilityError,
    TaskSchedulerService,
    WindowsTaskSchedulerAdapter,
)
from harness.automation.worker import PROTOCOL_VERSION, WorkerRequest, WorkerResponse
from harness.automation.pack import pack
from harness.automation.ports import (
    DesktopUiaPort,
    ExcelFilePort,
    HttpApiPort,
    SyncPlaywrightBrowserPort,
)
from harness.automation.workspace_runtime import (
    RuntimeManifest,
    WorkspaceRuntimeError,
    WorkspaceRuntimeIncompatibleError,
    WorkspaceRuntimeManager,
    WorkspaceStatus,
    default_manifest,
)

__all__ = [
    "AmbiguousWriteError",
    "ApprovalError",
    "ApprovalGrant",
    "AuthorityError",
    "AutomationApplication",
    "AutomationAction",
    "AutomationDefinition",
    "AutomationIntent",
    "AutomationProposal",
    "BudgetExhaustedError",
    "DefinitionVersion",
    "DiscoveryAdapter",
    "DiscoveryEvidence",
    "DuplicateWriteError",
    "EvidenceReference",
    "MappingSecretAdapter",
    "ApplicationResult",
    "Command",
    "Query",
    "Principal",
    "PrincipalError",
    "ReplayDivergenceError",
    "EvidenceStore",
    "ActionManifest",
    "SourceValidation",
    "SourceValidationError",
    "revision_identity",
    "validate_source",
    "PROTOCOL_VERSION",
    "WorkerRequest",
    "WorkerResponse",
    "FeatureSkill",
    "discover_skills",
    "get_skill",
    "ScheduledTaskRecord",
    "ScheduledTaskSpec",
    "SchedulerCapabilityError",
    "TaskSchedulerService",
    "WindowsTaskSchedulerAdapter",
    "ReconciliationError",
    "ReconciliationResult",
    "RepairError",
    "RepairProposal",
    "RepairTrialResult",
    "RepeatedTransitionError",
    "RunBudget",
    "RunSummary",
    "ProposalBudget",
    "ProposalModelAdapter",
    "ProposalValidation",
    "ProposalValidationError",
    "SelectorEvidence",
    "ToolResult",
    "VerificationResult",
    "WorkspaceRuntimeActiveError",
    "ACTION_CLASSES",
    "CapabilityExecutor",
    "CapabilityOp",
    "DesktopUiaPort",
    "ExcelFilePort",
    "FakeApi",
    "FakeBrowser",
    "FakeDesktop",
    "FakeExcel",
    "HttpApiPort",
    "SyncPlaywrightBrowserPort",
    "export_run_evidence",
    "run_evidence_payload",
    "pack",
    "proposal_from_dict",
    "RuntimeManifest",
    "WorkspaceRuntimeError",
    "WorkspaceRuntimeIncompatibleError",
    "WorkspaceRuntimeManager",
    "WorkspaceStatus",
    "default_manifest",
]
