name: theAutomationChallenge
log_level: INFO
report_dir: ./reports
screenshot_dir: ./screenshots
headless: false
browser: chromium
locale: en-US

variables:
  automation_challenge_url: https://www.theautomationchallenge.com/
  automation_challenge_output_dir: runs/the_automation_challenge
  automation_challenge_output_html: reports/the_automation_challenge/report_{timestamp}.html
